from typing import List

class ChatInfo:
    def __init__(self, chat_id: int, speaker: str, chat_content: str):
        self.chat_id = chat_id
        self.speaker = speaker
        self.chat_content = chat_content

chat_history: List[ChatInfo] = [
    ChatInfo(1, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(2, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(3, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(4, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(5, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(6, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(7, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(8, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(9, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(10, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(11, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(12, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(13, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(14, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(15, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(16, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(17, 'Alice', 'Nice! Where to?'),
    ChatInfo(18, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(19, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(20, 'Bob', 'We should go together sometime.'),
    ChatInfo(21, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(22, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(23, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(24, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(25, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(26, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(27, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(28, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(29, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(30, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(31, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(32, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(33, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(34, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(35, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(36, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(37, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(38, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(39, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(40, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ]

'''
    ChatInfo(41, 'Alice', 'Did you finish the book I lent you?'),
    ChatInfo(42, 'Bob', 'Not yet, but it\'s getting really good.'),
    ChatInfo(43, 'Alice', 'The ending is wild, just wait!'),
    ChatInfo(44, 'Bob', 'Can\'t wait to discuss it with you.'),
    ChatInfo(45, 'Alice', 'Next time we meet, let’s talk about it.'),
    ChatInfo(46, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(47, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(48, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(49, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(50, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(51, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(52, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(53, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(54, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(55, 'Alice', 'Nice! Where to?'),
    ChatInfo(56, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(57, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(58, 'Bob', 'We should go together sometime.'),
    ChatInfo(59, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(60, 'Bob', 'What are your plans for the weekend?'),
    ChatInfo(61, 'Alice', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(62, 'Bob', 'Nice! Where to?'),
    ChatInfo(63, 'Alice', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(64, 'Bob', 'I love that place. The views are amazing.'),
    ChatInfo(65, 'Alice', 'We should go together sometime.'),
    ChatInfo(66, 'Bob', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(67, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(68, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(69, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(70, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(71, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(72, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(73, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(74, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(75, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(76, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(77, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(78, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(79, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(80, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(81, 'Alice', 'Nice! Where to?'),
    ChatInfo(82, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(83, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(84, 'Bob', 'We should go together sometime.'),
    ChatInfo(85, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(86, 'Bob', 'What are your plans for the weekend?'),
    ChatInfo(87, 'Alice', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(88, 'Bob', 'Nice! Where to?'),
    ChatInfo(89, 'Alice', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(90, 'Bob', 'I love that place. The views are amazing.'),
    ChatInfo(91, 'Alice', 'We should go together sometime.'),
    ChatInfo(92, 'Bob', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(93, 'Alice', 'How\'s your project going at work?'),
    ChatInfo(94, 'Bob', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(95, 'Alice', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(96, 'Bob', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(97, 'Alice', 'I feel you. Let me know if you need help.'),
    ChatInfo(98, 'Bob', 'Thanks! Just talking helps a bit.'),
    ChatInfo(99, 'Alice', 'How\'s your project going at work?'),
    ChatInfo(100, 'Bob', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(101, 'Alice', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(102, 'Bob', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(103, 'Alice', 'I feel you. Let me know if you need help.'),
    ChatInfo(104, 'Bob', 'Thanks! Just talking helps a bit.'),
    ChatInfo(105, 'Alice', 'How\'s your project going at work?'),
    ChatInfo(106, 'Bob', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(107, 'Alice', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(108, 'Bob', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(109, 'Alice', 'I feel you. Let me know if you need help.'),
    ChatInfo(110, 'Bob', 'Thanks! Just talking helps a bit.'),
    ChatInfo(111, 'Alice', 'Did you finish the book I lent you?'),
    ChatInfo(112, 'Bob', 'Not yet, but it\'s getting really good.'),
    ChatInfo(113, 'Alice', 'The ending is wild, just wait!'),
    ChatInfo(114, 'Bob', 'Can\'t wait to discuss it with you.'),
    ChatInfo(115, 'Alice', 'Next time we meet, let’s talk about it.'),
    ChatInfo(116, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(117, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(118, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(119, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(120, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(121, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(122, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(123, 'Alice', 'Nice! Where to?'),
    ChatInfo(124, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(125, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(126, 'Bob', 'We should go together sometime.'),
    ChatInfo(127, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(128, 'Bob', 'I’m craving ramen today.'),
    ChatInfo(129, 'Alice', 'Me too! There’s a new place near the station.'),
    ChatInfo(130, 'Bob', 'Oh? What kind of ramen do they serve?'),
    ChatInfo(131, 'Alice', 'Tonkotsu mostly, but they have spicy miso too.'),
    ChatInfo(132, 'Bob', 'Sounds perfect. Let’s go there for lunch.'),
    ChatInfo(133, 'Alice', 'Great! I\'ll meet you at 12 then.'),
    ChatInfo(134, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(135, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(136, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(137, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(138, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(139, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(140, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(141, 'Alice', 'I’m craving ramen today.'),
    ChatInfo(142, 'Bob', 'Me too! There’s a new place near the station.'),
    ChatInfo(143, 'Alice', 'Oh? What kind of ramen do they serve?'),
    ChatInfo(144, 'Bob', 'Tonkotsu mostly, but they have spicy miso too.'),
    ChatInfo(145, 'Alice', 'Sounds perfect. Let’s go there for lunch.'),
    ChatInfo(146, 'Bob', 'Great! I\'ll meet you at 12 then.'),
    ChatInfo(147, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(148, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(149, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(150, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(151, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(152, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(153, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(154, 'Bob', 'What are your plans for the weekend?'),
    ChatInfo(155, 'Alice', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(156, 'Bob', 'Nice! Where to?'),
    ChatInfo(157, 'Alice', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(158, 'Bob', 'I love that place. The views are amazing.'),
    ChatInfo(159, 'Alice', 'We should go together sometime.'),
    ChatInfo(160, 'Bob', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(161, 'Alice', 'How\'s your project going at work?'),
    ChatInfo(162, 'Bob', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(163, 'Alice', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(164, 'Bob', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(165, 'Alice', 'I feel you. Let me know if you need help.'),
    ChatInfo(166, 'Bob', 'Thanks! Just talking helps a bit.'),
    ChatInfo(167, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(168, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(169, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(170, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(171, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(172, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(173, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(174, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(175, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(176, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(177, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(178, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(179, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(180, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(181, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(182, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(183, 'Alice', 'Nice! Where to?'),
    ChatInfo(184, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(185, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(186, 'Bob', 'We should go together sometime.'),
    ChatInfo(187, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(188, 'Bob', 'How\'s your project going at work?'),
    ChatInfo(189, 'Alice', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(190, 'Bob', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(191, 'Alice', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(192, 'Bob', 'I feel you. Let me know if you need help.'),
    ChatInfo(193, 'Alice', 'Thanks! Just talking helps a bit.'),
    ChatInfo(194, 'Bob', 'How\'s your project going at work?'),
    ChatInfo(195, 'Alice', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(196, 'Bob', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(197, 'Alice', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(198, 'Bob', 'I feel you. Let me know if you need help.'),
    ChatInfo(199, 'Alice', 'Thanks! Just talking helps a bit.'),
    ChatInfo(200, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(201, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(202, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(203, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(204, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(205, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(206, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(207, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(208, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(209, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(210, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(211, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(212, 'Bob', 'I’m craving ramen today.'),
    ChatInfo(213, 'Alice', 'Me too! There’s a new place near the station.'),
    ChatInfo(214, 'Bob', 'Oh? What kind of ramen do they serve?'),
    ChatInfo(215, 'Alice', 'Tonkotsu mostly, but they have spicy miso too.'),
    ChatInfo(216, 'Bob', 'Sounds perfect. Let’s go there for lunch.'),
    ChatInfo(217, 'Alice', 'Great! I\'ll meet you at 12 then.'),
    ChatInfo(218, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(219, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(220, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(221, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(222, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(223, 'Alice', 'What are your plans for the weekend?'),
    ChatInfo(224, 'Bob', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(225, 'Alice', 'Nice! Where to?'),
    ChatInfo(226, 'Bob', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(227, 'Alice', 'I love that place. The views are amazing.'),
    ChatInfo(228, 'Bob', 'We should go together sometime.'),
    ChatInfo(229, 'Alice', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(230, 'Bob', 'What are your plans for the weekend?'),
    ChatInfo(231, 'Alice', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(232, 'Bob', 'Nice! Where to?'),
    ChatInfo(233, 'Alice', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(234, 'Bob', 'I love that place. The views are amazing.'),
    ChatInfo(235, 'Alice', 'We should go together sometime.'),
    ChatInfo(236, 'Bob', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(237, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(238, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(239, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(240, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(241, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(242, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(243, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(244, 'Bob', 'I’m craving ramen today.'),
    ChatInfo(245, 'Alice', 'Me too! There’s a new place near the station.'),
    ChatInfo(246, 'Bob', 'Oh? What kind of ramen do they serve?'),
    ChatInfo(247, 'Alice', 'Tonkotsu mostly, but they have spicy miso too.'),
    ChatInfo(248, 'Bob', 'Sounds perfect. Let’s go there for lunch.'),
    ChatInfo(249, 'Alice', 'Great! I\'ll meet you at 12 then.'),
    ChatInfo(250, 'Bob', 'Hey, did you watch the movie last night?'),
    ChatInfo(251, 'Alice', 'Yeah, I did! It was pretty good.'),
    ChatInfo(252, 'Bob', 'I liked the main character, very intense.'),
    ChatInfo(253, 'Alice', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(254, 'Bob', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(255, 'Alice', 'Do you think it deserves the award?'),
    ChatInfo(256, 'Bob', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(257, 'Alice', 'Did you finish the book I lent you?'),
    ChatInfo(258, 'Bob', 'Not yet, but it\'s getting really good.'),
    ChatInfo(259, 'Alice', 'The ending is wild, just wait!'),
    ChatInfo(260, 'Bob', 'Can\'t wait to discuss it with you.'),
    ChatInfo(261, 'Alice', 'Next time we meet, let’s talk about it.'),
    ChatInfo(262, 'Bob', 'How\'s your project going at work?'),
    ChatInfo(263, 'Alice', 'It’s been hectic. Lots of last-minute changes.'),
    ChatInfo(264, 'Bob', 'That sounds stressful. Are you managing okay?'),
    ChatInfo(265, 'Alice', 'Trying to. Deadlines are killing me though.'),
    ChatInfo(266, 'Bob', 'I feel you. Let me know if you need help.'),
    ChatInfo(267, 'Alice', 'Thanks! Just talking helps a bit.'),
    ChatInfo(268, 'Bob', 'Did you finish the book I lent you?'),
    ChatInfo(269, 'Alice', 'Not yet, but it\'s getting really good.'),
    ChatInfo(270, 'Bob', 'The ending is wild, just wait!'),
    ChatInfo(271, 'Alice', 'Can\'t wait to discuss it with you.'),
    ChatInfo(272, 'Bob', 'Next time we meet, let’s talk about it.'),
    ChatInfo(273, 'Alice', 'Hey, did you watch the movie last night?'),
    ChatInfo(274, 'Bob', 'Yeah, I did! It was pretty good.'),
    ChatInfo(275, 'Alice', 'I liked the main character, very intense.'),
    ChatInfo(276, 'Bob', 'Same here. The plot twist at the end surprised me.'),
    ChatInfo(277, 'Alice', 'Totally. I didn\'t expect that at all.'),
    ChatInfo(278, 'Bob', 'Do you think it deserves the award?'),
    ChatInfo(279, 'Alice', 'Maybe, but the soundtrack could have been better.'),
    ChatInfo(280, 'Bob', 'What are your plans for the weekend?'),
    ChatInfo(281, 'Alice', 'I\'m thinking of going hiking if the weather is good.'),
    ChatInfo(282, 'Bob', 'Nice! Where to?'),
    ChatInfo(283, 'Alice', 'Probably Mount Takao. It\'s not too far.'),
    ChatInfo(284, 'Bob', 'I love that place. The views are amazing.'),
    ChatInfo(285, 'Alice', 'We should go together sometime.'),
    ChatInfo(286, 'Bob', 'Yeah, let\'s plan for next weekend!'),
    ChatInfo(287, 'Alice', 'I’m craving ramen today.'),
    ChatInfo(288, 'Bob', 'Me too! There’s a new place near the station.'),
    ChatInfo(289, 'Alice', 'Oh? What kind of ramen do they serve?'),
    ChatInfo(290, 'Bob', 'Tonkotsu mostly, but they have spicy miso too.'),
    ChatInfo(291, 'Alice', 'Sounds perfect. Let’s go there for lunch.'),
    ChatInfo(292, 'Bob', 'Great! I\'ll meet you at 12 then.'),
    ChatInfo(293, 'Alice', 'Did you finish the book I lent you?'),
    ChatInfo(294, 'Bob', 'Not yet, but it\'s getting really good.'),
    ChatInfo(295, 'Alice', 'The ending is wild, just wait!'),
    ChatInfo(296, 'Bob', 'Can\'t wait to discuss it with you.'),
    ChatInfo(297, 'Alice', 'Next time we meet, let’s talk about it.'),
    ChatInfo(298, 'Bob', 'I’m craving ramen today.'),
    ChatInfo(299, 'Alice', 'Me too! There’s a new place near the station.'),
    ChatInfo(300, 'Bob', 'Oh? What kind of ramen do they serve?'),
]
'''
